[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
play_halving = "3YeRxTdkC4h86P4o9sEbM5vvPVXczGTENnXJLMJQSnqG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./deployment.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init-program = "pnpm ts-node sdk/crank/initProgram.ts"
pause = "pnpm ts-node sdk/crank/pause.ts"
mark-halving = "pnpm ts-node sdk/crank/markHalving.ts"
close = "pnpm ts-node sdk/crank/close.ts"

[test.validator]
url = "http://localhost:8899" # This is the url of the cluster that accounts are cloned from (See `test.validator.clone`).
